## Kubernetes Advanced labs v1.5.0
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-quotas-example
spec:
  replicas: 2
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
            memory: 64Mi
