## Kubernetes Advanced labs v1.5.0
apiVersion: v1
kind: Pod
metadata:
  name: pod-qos-example
spec:
  containers:
  - name: pod-qos-example
    image: nginx
    resources:
      limits:
        memory: "200Mi"
        cpu: "700m"
      requests:
        memory: "200Mi"
        cpu: "700m"
